use_frameworks!

target 'SWRatingView_Example' do
  pod 'SWRatingView', :path => '../'

  target 'SWRatingView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
